POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Pertin blogi",
  "author": "Pertti",
  "url": "www.google.com",
  "likes": 0,
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Karin blogi",
  "author": "Kari",
  "url": "www.google.com",
  "likes": 0
}
